[package]
name = "webapp"
version = "0.1.0"
authors = ["Hassan Kaboyo"]


[dependencies]
iron = "0.5.1"
mime = "0.2.3"
router = "0.5.1"
urlencoded = "0.5.0"
rand = "0.3.0"
rustc-serialize = "0.3"
hyper = "0.12"

staticfile = "0.4.0"
mount = "0.3.0"
http = "0.1.7"
hyper-staticfile = "0.3.0"

